# Site settings
title: neilvyas
email: neilvyas@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  aut tace aut loquere meliora silencio
baseurl: "" 
url: "http://nvy.space" # the base hostname & protocol for your site
github_username:  neilvyas

# Build settings
markdown: kramdown
