# Site settings
title: Locutus
subtitle: "The Journal of Neil Vyas"
email: neilvyas@utexas.edu
description: "Studying pure mathematics at UT Austin, with an interest in finance, data visualization, statistics, and programming."
baseurl: ""
#url: "http://yourdomain.com"
#twitter_username: "rowanoulton"
github_username:  "neilvyas"
#instagram_username: "rowanoulton"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed