# Site settings
title: NeilVyas
email: neilvyas@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
    A collection of things I find interesting, primarily math and cs related.
    I'm a math major; my interests are primarily algebra and complex analysis.
    Currently, I work as a data science intern at Civitas Learning.
baseurl: "" 
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  neilvyas

# Build settings
markdown: kramdown
